const numberFormatter = new Intl.NumberFormat("ko-KR");
const decimalFormatter = new Intl.NumberFormat("ko-KR", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const fields = [["BAS_DD", "기준일", 105], ["ISU_CD", "종목코드", 105], ["ISU_NM", "종목명", 150], ["MKT_NM", "시장", 90], ["SECT_TP_NM", "소속부", 100], ["TDD_CLSPRC", "종가", 110, "number"], ["CMPPREVDD_PRC", "대비", 100, "number"], ["FLUC_RT", "등락률(%)", 105, "rate"], ["TDD_OPNPRC", "시가", 105, "number"], ["TDD_HGPRC", "고가", 105, "number"], ["TDD_LWPRC", "저가", 105, "number"], ["ACC_TRDVOL", "거래량", 125, "number"], ["ACC_TRDVAL", "거래대금", 145, "number"], ["MKTCAP", "시가총액", 160, "number"], ["LIST_SHRS", "상장주식수", 145, "number"]];
const numericFields = new Set(fields.filter(([, , , type]) => type === "number" || type === "rate").map(([field]) => field));
const columnDefs = fields.map(([field, headerName, width, type]) => ({ field, headerName, minWidth: width, filter: type ? "agNumberColumnFilter" : "agTextColumnFilter", type: type ? "rightAligned" : undefined, valueFormatter: ({ value }) => value === null || value === undefined || value === "" ? "-" : type === "rate" ? decimalFormatter.format(value) : type ? numberFormatter.format(value) : value, cellClass: field === "FLUC_RT" ? ({ value }) => value > 0 ? "up-value" : value < 0 ? "down-value" : "" : "" }));
const gridApi = agGrid.createGrid(document.querySelector("#stock-grid"), { theme: agGrid.themeQuartz, columnDefs, defaultColDef: { sortable: true, resizable: true, filter: true }, rowData: [], pagination: true, paginationPageSize: 100, paginationPageSizeSelector: [50, 100, 200, 500], animateRows: true, overlayNoRowsTemplate: '<span class="ag-overlay-no-rows-center">조회된 데이터가 없습니다.</span>' });
const fromInput = document.querySelector("#from-date"); const toInput = document.querySelector("#to-date"); const searchButton = document.querySelector("#search-button"); const csvButton = document.querySelector("#csv-button"); const status = document.querySelector("#status");
function isoDate(date) { return date.toISOString().slice(0, 10); }
const today = new Date(); const weekAgo = new Date(today); weekAgo.setDate(today.getDate() - 7); fromInput.value = isoDate(weekAgo); toInput.value = isoDate(today);
function setStatus(message, isError = false) { status.textContent = message; status.classList.toggle("error", isError); }
function updateSummary(data) { document.querySelector("#period-value").textContent = `${data.from_date} ~ ${data.to_date}`; document.querySelector("#days-value").textContent = `${numberFormatter.format(data.trading_days)}일`; document.querySelector("#records-value").textContent = `${numberFormatter.format(data.record_count)}건`; }
function flattenRecords(data) { return data.data.flatMap(({ records }) => records.map((record) => { const typed = { ...record }; numericFields.forEach((field) => { typed[field] = record[field] === "" ? null : Number(record[field]); }); return typed; })); }
async function loadData() { if (!fromInput.value || !toInput.value) return setStatus("시작일과 종료일을 입력하세요.", true); if (fromInput.value > toInput.value) return setStatus("시작일은 종료일보다 늦을 수 없습니다.", true); searchButton.disabled = true; csvButton.disabled = true; gridApi.setGridOption("rowData", []); setStatus("KRX 데이터를 조회하는 중입니다…"); try { const params = new URLSearchParams({ from: fromInput.value, to: toInput.value }); const response = await fetch(`/api/v1/stocks/daily?${params}`); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || "데이터를 불러오지 못했습니다."); const rows = flattenRecords(payload); gridApi.setGridOption("rowData", rows); updateSummary(payload); csvButton.disabled = rows.length === 0; setStatus(`${numberFormatter.format(rows.length)}건을 표시합니다. 열 제목을 클릭해 정렬하거나 필터를 사용하세요.`); } catch (error) { setStatus(error.message, true); } finally { searchButton.disabled = false; } }
searchButton.addEventListener("click", loadData); csvButton.addEventListener("click", () => gridApi.exportDataAsCsv({ fileName: `krx_daily_${fromInput.value}_${toInput.value}.csv` }));
